"""
Blockchain Setup & Deployment Script
Deploys the ModerationAudit smart contract and configures the system
"""

from web3 import Web3
from solcx import compile_standard, install_solc
import json
import os
from pathlib import Path


def compile_contract():
    """Compile the Solidity smart contract"""
    print("📦 Compiling smart contract...")
    
    # Install Solidity compiler
    install_solc('0.8.0')
    
    # Read contract source
    contract_path = Path("contracts/ModerationAudit.sol")
    with open(contract_path, 'r') as f:
        contract_source = f.read()
    
    # Compile
    compiled_sol = compile_standard(
        {
            "language": "Solidity",
            "sources": {
                "ModerationAudit.sol": {
                    "content": contract_source
                }
            },
            "settings": {
                "outputSelection": {
                    "*": {
                        "*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]
                    }
                }
            }
        },
        solc_version="0.8.0"
    )
    
    # Extract ABI and bytecode
    contract_data = compiled_sol['contracts']['ModerationAudit.sol']['ModerationAudit']
    abi = contract_data['abi']
    bytecode = contract_data['evm']['bytecode']['object']
    
    # Save ABI for later use
    abi_path = Path("contracts/ModerationAudit_abi.json")
    with open(abi_path, 'w') as f:
        json.dump(abi, f, indent=2)
    
    print(f"✓ Contract compiled successfully")
    print(f"✓ ABI saved to {abi_path}")
    
    return abi, bytecode


def deploy_contract(w3: Web3, account, private_key: str, abi: list, bytecode: str):
    """Deploy the smart contract to blockchain"""
    print("\n🚀 Deploying contract to blockchain...")
    
    # Create contract instance
    Contract = w3.eth.contract(abi=abi, bytecode=bytecode)
    
    # Build deployment transaction
    transaction = Contract.constructor().build_transaction({
        'from': account.address,
        'nonce': w3.eth.get_transaction_count(account.address),
        'gas': 3000000,
        'gasPrice': w3.eth.gas_price
    })
    
    # Sign transaction
    signed_txn = w3.eth.account.sign_transaction(transaction, private_key)
    
    # Send transaction
    print("📤 Sending deployment transaction...")
    tx_hash = w3.eth.send_raw_transaction(signed_txn.rawTransaction)
    
    # Wait for confirmation
    print("⏳ Waiting for confirmation...")
    tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
    
    if tx_receipt['status'] == 1:
        contract_address = tx_receipt['contractAddress']
        print(f"✓ Contract deployed successfully!")
        print(f"✓ Contract address: {contract_address}")
        print(f"✓ Transaction hash: {tx_hash.hex()}")
        print(f"✓ Gas used: {tx_receipt['gasUsed']}")
        return contract_address
    else:
        print("✗ Deployment failed")
        return None


def setup_environment_file(contract_address: str, network: str):
    """Create .env file with blockchain configuration"""
    env_path = Path(".env.blockchain")
    
    env_content = f"""# Blockchain Configuration for HarmLens
# Generated by blockchain_setup.py

# Ethereum Network Configuration
ETH_PROVIDER_URL={"http://127.0.0.1:8545" if network == "local" else "https://polygon-mumbai.infura.io/v3/YOUR_INFURA_KEY"}
CONTRACT_ADDRESS={contract_address}
ETH_PRIVATE_KEY=YOUR_PRIVATE_KEY_HERE

# IPFS Configuration
IPFS_GATEWAY=http://127.0.0.1:5001

# Webhook Configuration (optional)
WEBHOOK_HIGH_RISK=https://your-platform.com/webhooks/high-risk
WEBHOOK_CHILD_SAFETY=https://your-platform.com/webhooks/child-safety
WEBHOOK_ESCALATION=https://your-platform.com/webhooks/escalation

# Blockchain Features
USE_BLOCKCHAIN=true
USE_IPFS=true
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"\n✓ Environment file created: {env_path}")
    print("⚠️  Remember to update with your actual private key and API keys!")


def main():
    """Main setup flow"""
    print("=" * 60)
    print("HarmLens Blockchain Setup")
    print("=" * 60)
    
    # Choose network
    print("\nSelect network:")
    print("1. Local (Ganache/Hardhat)")
    print("2. Polygon Mumbai Testnet")
    print("3. Ethereum Sepolia Testnet")
    
    choice = input("\nEnter choice (1-3): ").strip()
    
    network_configs = {
        "1": ("local", "http://127.0.0.1:8545"),
        "2": ("mumbai", "https://polygon-mumbai.infura.io/v3/YOUR_INFURA_KEY"),
        "3": ("sepolia", "https://sepolia.infura.io/v3/YOUR_INFURA_KEY")
    }
    
    if choice not in network_configs:
        print("Invalid choice")
        return
    
    network_name, provider_url = network_configs[choice]
    
    # Get private key
    private_key = input("\nEnter your private key (or press Enter to skip deployment): ").strip()
    
    if not private_key:
        print("\n⚠️  Skipping deployment. Compiling contract only...")
        abi, bytecode = compile_contract()
        print("\n✓ Setup complete (compilation only)")
        return
    
    # Connect to network
    print(f"\n🔌 Connecting to {network_name}...")
    w3 = Web3(Web3.HTTPProvider(provider_url))
    
    if not w3.is_connected():
        print(f"✗ Failed to connect to {network_name}")
        print("For local network, make sure Ganache or Hardhat is running")
        return
    
    print(f"✓ Connected to {network_name}")
    print(f"✓ Chain ID: {w3.eth.chain_id}")
    
    # Load account
    account = w3.eth.account.from_key(private_key)
    balance = w3.eth.get_balance(account.address)
    print(f"✓ Account: {account.address}")
    print(f"✓ Balance: {w3.from_wei(balance, 'ether')} ETH")
    
    if balance == 0:
        print("\n⚠️  Warning: Account has zero balance!")
        print("You need ETH to deploy the contract")
        return
    
    # Compile contract
    abi, bytecode = compile_contract()
    
    # Deploy contract
    contract_address = deploy_contract(w3, account, private_key, abi, bytecode)
    
    if contract_address:
        # Setup environment file
        setup_environment_file(contract_address, network_name)
        
        print("\n" + "=" * 60)
        print("✓ Setup Complete!")
        print("=" * 60)
        print(f"\nContract Address: {contract_address}")
        print(f"Network: {network_name}")
        print(f"\nNext steps:")
        print("1. Update .env.blockchain with your actual keys")
        print("2. Start IPFS daemon: ipfs daemon")
        print("3. Run the API server: python api_server.py")
        print("=" * 60)


if __name__ == "__main__":
    main()
